# SPDX-License-Identifier: MIT
# STRATAGEM DARK prototype defaults; include explicitly after review.
$mainMod = SUPER
$terminal = foot
bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod SHIFT, Q, killactive,
bind = $mainMod, F, fullscreen,
general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2
    col.active_border = rgb(a7f3a0)
    col.inactive_border = rgb(314038)
}
animations {
    enabled = false
}
