o.rebind("SUPER + RETURN", "Terminal", "foot")
o.rebind("SUPER + SPACE", "STRATAGEM DARK menu", "stratagem-shell shell toggle stratagem.menu")
o.rebind("SUPER + B", "Browser", "firefox")
o.rebind("SUPER + E", "Files", "thunar")
o.rebind("SUPER + CTRL + L", "Lock session", "hyprlock")
o.rebind("SUPER + SHIFT + A", "Agent workspace", "foot dark desktop agents")
o.rebind("SUPER + K", "Keyboard shortcuts", "foot dark desktop help")
o.rebind("SUPER + A", "New authorized engagement", "foot dark desktop engagement")
o.rebind("SUPER + T", "Tool cheat sheet", "foot dark desktop cheatsheet")
