background {
    path = /usr/share/stratagem-dark/branding/wallpaper.png
}
input-field {
    size = 300, 50
    position = 0, -180
    outline_thickness = 2
    outer_color = rgb(a7f3a0)
    inner_color = rgb(101512)
    font_color = rgb(a7f3a0)
    placeholder_text = STRATAGEM DARK
}
