source = ~/.local/state/stratagem/current/theme/hyprlock-colors.conf
background {
    path = /usr/share/stratagem-dark/branding/wallpaper.png
}
input-field {
    size = 300, 50
    position = 0, -180
    outline_thickness = 2
    outer_color = $theme_foreground
    inner_color = $theme_background
    font_color = $theme_foreground
    placeholder_text = STRATAGEM DARK
}
